config/routes.rb
Pictorealm::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :songs
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name, :yt_id
  belongs_to :user, :foreign_key => :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

  has_many :songs, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_filter :signed_in

	def index
		@songs = current_user.songs
		@rand = @songs[rand(@songs.length)].yt_id unless @songs.empty?
		@song = Song.new
	end

	def create
		current_user.songs.create params[:song]
		flash[:notice] = "Song successfully added"
		return redirect_to index
	end

	def destroy
		Song.find(params[:id]).destroy
		return redirect_to index
	end

	def show
		@yt_id = Song.find(params[:id]).yt_id || 0
		@songs = current_user.songs
	end

private
	 def signed_in
    unless user_signed_in?
      flash[:error] = "Please sign in to continue"
      return redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scraper.rb
require 'open-uri'

class Scraper 

  attr_accessor :link

  def initialize(link)
    @link = link
  end

  def build_link
    scraped = build_results_hash
    
    usr = scraped[:username]
    song_id = scraped[:song_id]
    audio_id = scraped[:audio_id]
    plead = "?plead=please-dont-download-this-or-our-lawyers-wont-let-us-host-audio"

    tumblr_link = 'http://www.tumblr.com/audio_file/'        
    tumblr_link << usr << ?/ << song_id << '/tumblr_' << audio_id << plead
    tumblr_link
  end

  def scrape
    open(@link).read
  end

  def build_results_hash
    match = scrape.match(tumblr_regex)
    results = Hash.new
    1.upto(match.names.length) do |idx|
        results[match.names[idx-1].to_sym] = match[idx]
      end
    results
  end

  def tumblr_regex
    /audio_file\/(?<username>.+)\/(?<song_id>\d+)\/tumblr_(?<audio_id>.+)&color/
  end

end


#http://www.tumblr.com/audio_file/kaepop/11352761077/tumblr_lsvm9fk2Qw1qcup2x?plead=please-dont-download-this-or-our-lawyers-wont-let-us-host-audio

#http://www.tumblr.com/audio_file/kaepop/11352761077/tumblr_lsvm9fk2Qw1qcup2x

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    
  </body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">

  <% if user_signed_in? %>
    <li>
    <%= link_to 'Songs', songs_path %>
    </li>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>

    <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VIP Playlister" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "VIP Playlister" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/songs/index.html.erb
<div class ="row">
	
	<div class = "span8">
		<h3> Songs </h3><br>
		<% if @songs.length > 0 then %>
		<% @songs.each do |song| %>
		<%= song.name %>
		<%= link_to "play", song, :remote => true %>
		<%= link_to "delete", song, method: :delete %>
		<br>
		<% end %>
		<% else %>
		No songs to display
		<% end %>
	</div>

	<div class ="span4">
		<h3>Video</h3><br><% if @rand then %>
		<div id="tabs2"><iframe width="200"height="200"frameborder="0" type="text/html"src="http://www.youtube.com/embed/<%= @rand %>?enablejsapi=1"></iframe></div>
		<script>

    function getFrameID(id){
        var elem = document.getElementById(id);
        if (elem) {
            if(/^iframe$/i.test(elem.tagName)) return id; //Frame, OK
            // else: Look for frame
            var elems = elem.getElementsByTagName("iframe");
            if (!elems.length) return null; //No iframe found, FAILURE
            for (var i=0; i<elems.length; i++) {
               if (/^https?:\/\/(?:www\.)?youtube(?:-nocookie)?\.com(\/|$)/i.test(elems[i].src)) break;
            }
            elem = elems[i]; //The only, or the best iFrame
            if (elem.id) return elem.id; //Existing ID, return it
            // else: Create a new ID
            do { //Keep postfixing `-frame` until the ID is unique
                id += "-frame";
            } while (document.getElementById(id));
            elem.id = id;
            return id;
        }
        // If no element, return null.
        return null;
    }

    // Define YT_ready function.
    var YT_ready = (function(){
        var onReady_funcs = [], api_isReady = false;
        /* @param func function     Function to execute on ready
         * @param func Boolean      If true, all qeued functions are executed
         * @param b_before Boolean  If true, the func will added to the first
                                     position in the queue*/
        return function(func, b_before){
            if (func === true) {
                api_isReady = true;
                for (var i=0; i<onReady_funcs.length; i++){
                    // Removes the first func from the array, and execute func
                    onReady_funcs.shift()();
                }
            }
            else if(typeof func == "function") {
                if (api_isReady) func();
                else onReady_funcs[b_before?"unshift":"push"](func); 
            }
        }
    })();
    // This function will be called when the API is fully loaded
    function onYouTubePlayerAPIReady() {YT_ready(true)}

    // Load YouTube Frame API
    (function(){ //Closure, to not leak to the scope
      var s = document.createElement("script");
      s.src = "http://www.youtube.com/player_api"; /* Load Player API*/
      var before = document.getElementsByTagName("script")[0];
      before.parentNode.insertBefore(s, before);
    })();

    var player; //Define a player object, to enable later function calls, without
                // having to create a new class instance again.

    // Add function to execute when the API is ready
    YT_ready(function(){
        var frameID = getFrameID("tabs2");
        if (frameID) { //If the frame exists
            player = new YT.Player(frameID, {
                events: {
                    "onStateChange": stopCycle
                }
            });
        }
    });

function callPlayer(frame_id, func, args) {
    if (window.jQuery && frame_id instanceof jQuery) frame_id = frame_id.get(0).id;
    var iframe = document.getElementById(frame_id);
    if (iframe && iframe.tagName.toUpperCase() != 'IFRAME') {
        iframe = iframe.getElementsByTagName('iframe')[0];
    }

    // When the player is not ready yet, add the event to a queue
    // Each frame_id is associated with an own queue.
    // Each queue has three possible states:
    //  undefined = uninitialised / array = queue / 0 = ready
    if (!callPlayer.queue) callPlayer.queue = {};
    var queue = callPlayer.queue[frame_id],
        domReady = document.readyState == 'complete';

    if (domReady && !iframe) {
        // DOM is ready and iframe does not exist. Log a message
        window.console && console.log('callPlayer: Frame not found; id=' + frame_id);
        if (queue) clearInterval(queue.poller);
    } else if (func === 'listening') {
        // Sending the "listener" message to the frame, to request status updates
        if (iframe && iframe.contentWindow) {
            func = '{"event":"listening","id":' + JSON.stringify(''+frame_id) + '}';
            iframe.contentWindow.postMessage(func, '*');
        }
    } else if (!domReady || iframe && (!iframe.contentWindow || queue && !queue.ready)) {
        if (!queue) queue = callPlayer.queue[frame_id] = [];
        queue.push([func, args]);
        if (!('poller' in queue)) {
            // keep polling until the document and frame is ready
            queue.poller = setInterval(function() {
                callPlayer(frame_id, 'listening');
            }, 250);
            // Add a global "message" event listener, to catch status updates:
            messageEvent(1, function runOnceReady(e) {
                var tmp = JSON.parse(e.data);
                if (tmp && tmp.id == frame_id && tmp.event == 'onReady') {
                    // YT Player says that they're ready, so mark the player as ready
                    clearInterval(queue.poller);
                    queue.ready = true;
                    messageEvent(0, runOnceReady);
                    // .. and release the queue:
                    while (tmp = queue.shift()) {
                        callPlayer(frame_id, tmp[0], tmp[1]);
                    }
                }
            }, false);
        }
    } else if (iframe && iframe.contentWindow) {
        // When a function is supplied, just call it (like "onYouTubePlayerReady")
        if (func.call) return func();
        // Frame exists, send message
        iframe.contentWindow.postMessage(JSON.stringify({
            "event": "command",
            "func": func,
            "args": args || [],
            "id": frame_id
        }), "*");
    }
    /* IE8 does not support addEventListener... */
    function messageEvent(add, listener) {
        var w3 = add ? window.addEventListener : window.removeEventListener;
        w3 ?
            w3('message', listener, !1)
        :
            (add ? window.attachEvent : window.detachEvent)('onmessage', listener);
    }
}

		callPlayer('tabs2','playVideo')

    // Example: function stopCycle, bound to onStateChange
    function stopCycle(event) {
			  if (event.data == YT.PlayerState.ENDED) {
         	callPlayer('tabs2','loadVideoById',['<%= @songs[rand(@songs.length)].yt_id %>']) 
        }
        
    }

</script>
​
		<% else %>
		Add some songs first!
		<% end %>

		<br><h3> Add Song </h3><br>
		<%= form_for @song, :url => { :action => 'create' } do |f| %>
			
			<%= f.label "Song Name" %>
			<%= f.text_field :name %>

			<%= f.label "Youtube ID" %>
			<%= f.text_field :yt_id %>
			<%= f.submit "+" %>
		<% end %>

		</div>
			
	</div>

</div>

app/views/songs/show.js.erb
callPlayer('tabs2','loadVideoById',['<%= @yt_id %>'])

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>